version: "3.8"
services:
  homework-03:
    image: kellucd/lab-03:latest
    build: .
    container_name: lab03
    ports:
      - "80:3700"
    environment:
      - PORT=3700
    volumes:
      - ./:/app
    command: ["node", "index.js"]
      
